export type PlaceDescriptionUpdate = {
  slug: string;
  ru: string;
  en: string;
  zh: string;
  /** Localized display name for EN locale (optional). */
  nameEn?: string;
  /** Localized display name for ZH locale (optional). */
  nameZh?: string;
  /** Localized address used in the EN description suffix (optional). */
  addressEn?: string;
  /** Localized address used in the ZH description suffix (optional). */
  addressZh?: string;
};

/** Approved about-text bodies. Address suffixes are attached at write time. */
export const PLACE_DESCRIPTION_UPDATES: PlaceDescriptionUpdate[] = [
  {
    slug: "sobranie-speshilova",
    ru: "Выставка самоваров в комплексе «Собрание Спешилова» — уникальный объект культурного и исторического наследия не только Иркутской области, подобной коллекции нет на всем пространстве от Урала до Дальнего Востока. Эта постоянная выставка и всегда открыта для гостей комплекса. Коллекция самоваров насчитывает более 350 редких экземпляров, изготовленных различными фабриками и мастерскими России и Зарубежья начиная с XVIII века.",
    en: "The samovar exhibition at the Sobranie Speshilova complex is a unique cultural and historical landmark — not only for the Irkutsk Region. There is no comparable collection anywhere from the Urals to the Far East. This is a permanent exhibition, always open to guests of the complex. The collection numbers more than 350 rare samovars made by factories and workshops in Russia and abroad from the 18th century onward.",
    zh: "馆内珍藏超过350件18世纪以来的俄罗斯及海外精美铜壶，是乌拉尔山脉以东规模最大、最完整的茶炊收藏。这里不仅是餐厅，更是一座活态文化博物馆。",
    nameEn: "Sobranie Speshilova Gallery-Restaurant Complex",
    nameZh: "斯佩希洛夫收藏馆 · 画廊餐厅",
    addressEn: "Irkutsk, Sedova 42/1",
    addressZh: "谢多娃街 42/1",
  },
  {
    slug: "knyaz-gvidon",
    ru: "Истинное волшебство «Князя Гвидона» ощущается не только на вкус. Интерьеры ресторана оживляют узнаваемые элементы любимой сказки А.С. Пушкина. Каждая деталь — от тщательно выверенного освещения до благородных текстур материалов — подчеркивает уникальность заведения. Особую гордость представляют стены ресторана, расписанные вручную с использованием техники фрески, что создает неповторимый художественный эффект.",
    en: "The true magic of Prince Gvidon is not only on the plate. The interiors bring to life recognizable details of Pushkin’s beloved fairy tale. Every element — from carefully calibrated lighting to noble material textures — underlines the venue’s character. A special pride is the restaurant’s walls, hand-painted in fresco technique, creating a one-of-a-kind artistic effect.",
    zh: "普希金童话世界的现实版。手工湿壁画、考究光影、典雅质感，每一处细节都让人仿佛置身童话之中。",
    nameEn: "Prince Gvidon Restaurant",
    nameZh: "格维东公爵餐厅",
    addressEn: "Irkutsk, Sukhe-Bator St., 18",
    addressZh: "苏赫巴托尔街 18",
  },
  {
    slug: "restoran-ohotnikov",
    ru: "Когда-то сюда приходили те, кто хорошо знал тайгу. Люди, для которых Сибирь была не точкой на карте, а частью жизни. Они знали цену настоящему продукту, уважали силу природы и понимали: лучшие истории рождаются не в дороге, а после неё — за большим столом, у живого огня. Так появилось место, которое назвали «Охотников». Сегодня здесь рады не только тем, кто бывал в тайге. Но и тем, кто только хочет открыть для себя настоящую Сибирь.",
    en: "Once, people who knew the taiga well came here. People for whom Siberia was not a point on a map, but part of life. They knew the worth of a true product, respected the power of nature, and understood that the best stories are born not on the road, but after it — at a long table, by a live fire. That is how the place called “Okhotnikov” appeared. Today it welcomes not only those who have been to the taiga, but also those who want to discover the real Siberia.",
    zh: "曾几何时，熟悉泰加林的人们在此相聚。对他们而言，西伯利亚不只是地图上的一处坐标，而是生命的一部分；他们珍视本真的食材，敬畏自然的力量，也深知最动人的故事，总在旅途归来后，于长桌旁、炉火边缓缓展开。于是，“猎人餐厅”应运而生。如今，这里不仅欢迎曾踏足泰加林的旅人，也欢迎所有渴望体验真正西伯利亚的人。",
    nameEn: "Okhotnikov Restaurant",
    nameZh: "猎人餐厅",
    addressEn: "Irkutsk, Yadrintsev St., 1zh",
    addressZh: "亚德林采娃街 1ж",
  },
  {
    slug: "baikal-severnoe-more",
    ru: "Шеф-меню ресторана сочетает европейские и китайские гастрономические традиции. Идеальное место для гастрономических впечатлений с видом на Ангару.",
    en: "The chef’s menu brings together European and Chinese culinary traditions. An ideal place for a gastronomic experience with a view of the Angara.",
    zh: "餐厅主厨菜单巧妙融合欧洲与中华烹饪传统，在不同风味的交汇中呈现令人回味的美食体验。在安加拉河畔，一边欣赏美景，一边享受美食，开启一段难忘的味觉体验。",
    nameEn: "Baikal – Northern Sea Restaurant",
    nameZh: "贝加尔 · 北海餐厅",
    addressEn: "Irkutsk, Dalnevostochnaya St., 156",
    addressZh: "远东街 156",
  },
  {
    slug: "chento",
    ru: "Итальянская кухня, изысканные вина и уютная атмосфера. Chento — место для ваших лучших моментов.",
    en: "Italian cuisine, fine wines, and a cozy atmosphere. Chento is a place for your best moments.",
    zh: "意式温情，精致美酒，舒适氛围——这里是美好时光的容器。",
    nameEn: "Chento Restaurant",
    nameZh: "Chento 意大利餐厅",
    addressEn: "Irkutsk, 3 July St., 1a",
    addressZh: "7月3日街 1а",
  },
  {
    slug: "prego",
    ru: "Итальянский ресторан с 15-летней историей, где каждое блюдо готовится с любовью и по традиционным рецептам!",
    en: "An Italian restaurant with a 15-year history, where every dish is cooked with care and traditional recipes!",
    zh: "15年匠心传承，每道菜都按传统配方精心烹制。家的味道，意式风情。",
    nameEn: "Prego Restaurant",
    nameZh: "Prego 意大利餐厅",
    addressEn: "Irkutsk, Karl Marx St., 15A",
    addressZh: "卡尔·马克思街 15А",
  },
  {
    slug: "vyuga-mayak",
    ru: "Ресторан «VYЮГА» — гастрономическое приключение и погружение в Сибирскую кухню. Все блюда — это шедевр и, конечно, потрясающий вид на озеро Байкал!",
    en: "Restaurant “VYUGA” is a gastronomic adventure and a dive into Siberian cuisine. Every dish is a masterpiece — and of course there is a stunning view of Lake Baikal!",
    zh: "一场舌尖上的西伯利亚探险。每道菜都是杰作，窗外便是壮阔的贝加尔湖。",
    nameEn: "VYUGA Restaurant",
    nameZh: "VYЮГA 风雪餐厅",
    addressEn: "Listvyanka, Gorky St., 85A",
    addressZh: "利斯特维扬卡镇，高尔基街 85А",
  },
  {
    slug: "mangal",
    ru: "Гриль-ресторан с летней верандой. 10 лет непревзойденного качества и прекрасный вид на залив.",
    en: "A grill restaurant with a summer terrace. Ten years of outstanding quality and a beautiful view of the bay.",
    zh: "烧烤餐厅，设有夏日露台。十年品质保证，享受美食的同时，欣赏美丽的海湾景色。",
    nameEn: "Mangal Restaurant",
    nameZh: "烤炉餐厅",
    addressEn: "Irkutsk, Bezobokov St., 1, building 1",
    addressZh: "别兹博科娃街 1号，1栋",
  },
  {
    slug: "butin",
    ru: "Здесь каждый может отдохнуть \"без галстука\", побыть собой, хорошо и вкусно провести время в ресторане. Именно здесь, в Хасановском переулке, с 1872-го года были знаменитые винные погреба нерчинского миллионера Михаила Бутина — предпринимателя, общественного деятеля, мецената, истинного патриота и просто очень разностороннего и интересного человека из истории нашего города.",
    en: "Here anyone can unwind “without a tie”, be themselves, and enjoy good food and good company at the restaurant. It was here, on Khasanovsky Lane, that from 1872 stood the famous wine cellars of Nerchinsk millionaire Mikhail Butin — entrepreneur, public figure, patron of the arts, a true patriot, and a remarkably many-sided figure in our city’s history.",
    zh: "在这里，您可以轻松自在地做自己，与朋友相聚，品尝美食，享受愉快时光。餐厅位于哈萨诺夫巷。自 1872 年起，这里曾是涅尔琴斯克商人米哈伊尔·布京的著名葡萄酒窖。布京不仅是一位成功的企业家，也是一位社会活动家和慈善家。他热爱家乡，为这座城市留下了一段值得铭记的历史。",
    nameEn: "Butin Restaurant",
    nameZh: "Butin餐厅",
    addressEn: "Irkutsk, Khasanovsky Lane, 1",
    addressZh: "哈萨诺夫斯基巷 1",
  },
  {
    slug: "kurbatov",
    ru: "Ресторан Kurbatov — это гастрономический символ современной Сибири в интерьерах светского «Сибирского Петербурга», расположенный на берегу реки Ангары. Авторская кухня, основанная на локальных ингредиентах и тонкой работе с традициями. Меню строится вокруг сезонных и фермерских продуктов, в том числе эндемиков Приангарья.",
    en: "Kurbatov is a gastronomic symbol of contemporary Siberia in the interiors of a worldly “Siberian Petersburg”, on the bank of the Angara. Author’s cuisine grounded in local ingredients and a fine reading of tradition. The menu is built around seasonal and farm products, including endemics of the Angara region.",
    zh: "安加拉河畔的“西伯利亚彼得堡”。主厨创意料理以当地食材为核心，在尊重传统的基础上赋予风味新的表达。菜单精选时令与农场食材，更融入安加拉河地区独有的珍稀物产，让每一道菜都带来纯正的西伯利亚味道。",
    nameEn: "Kurbatov Restaurant",
    nameZh: "Kurbatov餐厅",
    addressEn: "Irkutsk, Nikolai Gavrilov St., 2",
    addressZh: "尼古拉·加夫里洛夫街 2",
  },
  {
    slug: "evropa",
    ru: "Ресторан «Европа» — одно из самых стильных заведений города, островок доброжелательности, отменного вкуса и гостеприимства. Сюда устремляются страстные почитатели вкусной еды, изысканных напитков, и просто те, кто умеет распознавать неповторимый вкус и аромат самой жизни.",
    en: "Restaurant “Evropa” is one of the city’s most stylish venues — an island of warmth, excellent taste, and hospitality. Passionate lovers of good food and refined drinks come here, as do those who know how to recognize the unique flavor and aroma of life itself.",
    zh: "“欧洲”餐厅是城里很有格调的餐厅之一。在这里，您可以享受美味佳肴、精选饮品和热情周到的服务。无论是喜爱美食美酒，还是想与亲友共度美好时光，这里都是很好的选择。",
    nameEn: "Evropa Restaurant",
    nameZh: "欧洲餐厅",
    addressEn: "Irkutsk, Baikalskaya St., 69",
    addressZh: "贝加尔街 69",
  },
  {
    slug: "klyukva-baykalsk",
    ru: "В ресторане «Клюква» гости могут полноценно отдохнуть от прогулок по живописным окрестностям и насладиться уникальными блюдами сибирской кухни в атмосфере тепла и уюта. «Клюква» славится своим разнообразным меню, предлагающим блюда из свежих и местных ингредиентов, а также изысканные напитки.",
    en: "At restaurant “Klyukva”, guests can fully rest after walks through scenic surroundings and enjoy distinctive Siberian dishes in an atmosphere of warmth and comfort. “Klyukva” is known for a varied menu of fresh local ingredients, as well as refined drinks.",
    zh: "在“蔓越莓”餐厅，您可以暂别周边美景中的漫步时光，在温暖舒适的氛围里，好好放松，品尝西伯利亚料理。餐厅菜单丰富，精选新鲜本地食材制作各式佳肴，并提供精致饮品，为您的旅程增添一份美好的味觉记忆。",
    nameEn: "Klyukva Restaurant",
    nameZh: "蔓越莓餐厅",
    addressEn: "Baikalsk, Krasny Klyuch microdistrict, 93",
    addressZh: "贝加尔斯克市，红泉小区 93号",
  },
  {
    slug: "pepel",
    ru: "Пепел — след открытий сибирского путешественника. Проект вдохновлен величием Долины вулканов и загадочной судьбой иркутского геолога — исследователя Перетолчина. Каждый элемент — прикосновение к атмосфере странствий отважного путешественника, а блюда — как страницы его дневника.",
    en: "Pepel is the trace of a Siberian traveler’s discoveries. The project is inspired by the grandeur of the Valley of Volcanoes and the mysterious fate of Irkutsk geologist-explorer Peretolchin. Every element touches the atmosphere of a brave traveler’s journeys, and the dishes read like pages of his diary.",
    zh: "致敬西伯利亚探险家佩列托尔钦的传奇旅程。餐厅的每一处细节，都让人仿佛走进这位勇敢旅者的探索之路；而每一道菜，则如同翻开他探险日记中的一页。",
    nameEn: "Pepel Restaurant",
    nameZh: "灰烬餐厅",
    addressEn: "Irkutsk, Sukhe-Bator St., 6",
    addressZh: "苏赫巴托尔街 6",
  },
  {
    slug: "kitayskiy-ieroglif",
    ru: "«Китайский Иероглиф» — первый китайский ресторан в Иркутске! Китайские повара готовят для гостей блюда по традиционным рецептам.",
    en: "“Chinese Hieroglyph” is the first Chinese restaurant in Irkutsk! Chinese chefs cook for guests from traditional recipes.",
    zh: "伊尔库茨克第一家真正的中餐厅。中国大厨掌勺，老配方，老味道。",
    nameEn: "Chinese Hieroglyph Restaurant",
    nameZh: "中国汉字餐厅",
    addressEn: "Irkutsk, Yadrintsev St., 1Zh",
    addressZh: "亚德林采娃街 1Ж",
  },
  {
    slug: "pappare",
    ru: "Теплый свет, натуральное дерево, живые растения и итальянская кухня без лишнего пафоса. Место, где вечер становится мягче.",
    en: "Warm light, natural wood, living plants, and Italian cooking without extra pomp. A place where the evening grows softer.",
    zh: "暖光、原木、绿植，意式简餐。没有过度修饰，只有治愈的夜晚。",
    nameEn: "Pappare Italian Trattoria",
    nameZh: "帕帕雷意大利小馆",
    addressEn: "Irkutsk, Bogdanov Lane, 4",
    addressZh: "波格丹诺夫巷 4",
  },
  {
    slug: "chempiony",
    ru: "Это не просто бар или ресторан, а ещё и музей Иркутского спорта с мужской игровой комнатой и караоке. Море еды и трансляции спортивных матчей.",
    en: "Not just a bar or restaurant — also a museum of Irkutsk sport, with a men’s game room and karaoke. Plenty of food and live sports broadcasts.",
    zh: "不止是酒馆，更是伊尔库茨克体育博物馆。男士游戏房、卡拉OK、体育赛事直播，美食管够。",
    nameEn: "Champions Gastrobar",
    nameZh: "冠军美食酒吧",
    addressEn: "Irkutsk, Karl Marx St., 21",
    addressZh: "卡尔·马克思街 21",
  },
  {
    slug: "kruzhal",
    ru: "\"Кружаль\" — то, что русской душе угодно! Это место для веселых людей и отвязных вечеринок. Каждый месяц — новая программа.",
    en: "“Kruzhal” is what a Russian soul wants! A place for cheerful people and uninhibited parties. A new program every month.",
    zh: "一个专为快乐灵魂打造的狂欢地。这里属于热爱热闹、喜欢派对的人。每个月都有全新主题和精彩活动，让欢乐从不重复。",
    nameEn: "Kruzhal Gastrobar",
    nameZh: "欢聚美食酒吧",
    addressEn: "Irkutsk, 3 July St., 1A",
    addressZh: "7月3日街 1А",
  },
  {
    slug: "red-grot",
    ru: "Ресторан и бар у залива. С 2012 года. Сюда приходят за душевным ужином и разговорами с друзьями.",
    en: "A restaurant and bar by the bay. Since 2012. People come for a heartfelt dinner and conversations with friends.",
    zh: "自2012年起，静静守在港湾旁。人们来此，只为好好吃顿饭，好好聊聊天。",
    nameEn: "Red Grot Restaurant & Bar",
    nameZh: "Red Grot\"餐厅酒吧",
    addressEn: "Irkutsk, Marshal Zhukov St., 15/2",
    addressZh: "朱可夫元帅街 15/2",
  },
  {
    slug: "yabloko",
    ru: "Ресторан и караоке про счастливую жизнь.",
    en: "A restaurant and karaoke about a happy life.",
    zh: "美食与卡拉OK合体，唱响快乐人生。",
    nameEn: "Yabloko Restaurant",
    nameZh: "苹果餐厅",
    addressEn: "Irkutsk, Partizanskaya St., 28a/1",
    addressZh: "游击队员街 28а/1",
  },
  {
    slug: "kochevnik",
    ru: "Одно из самых необычных мест города. Здесь, благодаря уникальному этническому интерьеру, Вы окунетесь в атмосферу времен Золотой Орды. Попробуете блюда, которые подавали самому Чингисхану.",
    en: "One of the city’s most unusual places. Thanks to a unique ethnic interior, you step into the atmosphere of the Golden Horde. Try dishes once served to Genghis Khan himself.",
    zh: "极富民族风情的空间，仿佛回到金帐汗国时代。据说，这里的菜肴当年曾上过成吉思汗的餐桌。",
    nameEn: "Kochevnik Mongolian Restaurant",
    nameZh: "游牧民族蒙古餐厅",
    addressEn: "Irkutsk, Gorky St., 19",
    addressZh: "高尔基街 19",
  },
  {
    slug: "grot-pervomayskiy",
    ru: "Деловые обеды, дружеские посиделки, яркие праздники и семейные вечера — всё это ждёт вас в ресторане с европейской кухней, живой атмосферой и заботой о каждом госте!",
    en: "Business lunches, friendly get-togethers, bright celebrations, and family evenings — all await you in a restaurant with European cuisine, a lively atmosphere, and care for every guest!",
    zh: "商务午餐、朋友小聚、欢乐庆典，或温馨的家庭晚餐—这里都能满足您的期待。餐厅提供欧式美食，氛围轻松热闹，并用心关照每一位客人。",
    nameEn: "Grot Pervomayskiy Restaurant",
    nameZh: "五一区洞穴餐厅",
    addressEn: "Irkutsk, Pervomayskiy microdistrict, 14A",
    addressZh: "五一小区 14А",
  },
];
